
CREATE TABLE TODOUSER.PROJECT(
    PROJECT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(4000) NOT NULL
);

CREATE TABLE TODOUSER.SPRINT(
    SPRINT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_ID NUMBER NOT NULL,
    NAME VARCHAR2(4000) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    CONSTRAINT SPRINT_FK FOREIGN KEY(PROJECT_ID) 
    REFERENCES TODOUSER.PROJECT(PROJECT_ID) ON DELETE CASCADE
);

CREATE TABLE TODOUSER.EMPLOYEE(
    EMPLOYEE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(4000) NOT NULL,
    MANAGER_ID NUMBER,
    EMAIL VARCHAR2(320) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    PROJECT_ID NUMBER NOT NULL,
    TELEGRAM_ID NUMBER(20),
    CONSTRAINT EMPLOYEE_PROJECT_FK FOREIGN KEY(PROJECT_ID)
    REFERENCES TODOUSER.PROJECT(PROJECT_ID) ON DELETE CASCADE
);

ALTER TABLE TODOUSER.EMPLOYEE
ADD CONSTRAINT EMPLOYEE_EMPLOYEE_FK FOREIGN KEY(MANAGER_ID) 
REFERENCES TODOUSER.EMPLOYEE(EMPLOYEE_ID);

CREATE TABLE TODOUSER.TODOITEM(
    TODOITEM_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK(STATUS IN ('COMPLETED', 'PENDING', 'CANCELLED', 'REVIEWING')),
    MANAGER_ID NUMBER NOT NULL,
    COMPLETION_TS TIMESTAMP WITH TIME ZONE,
    START_DATE TIMESTAMP WITH TIME ZONE,
    DEADLINE TIMESTAMP WITH TIME ZONE,
    SPRINT_ID NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(4000),
    EST_HOURS NUMBER NOT NULL,
    CONSTRAINT TODOITEM_EMPLOYEE_FK FOREIGN KEY(MANAGER_ID) REFERENCES TODOUSER.EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT TODOITEM_SPRINT_FK FOREIGN KEY(SPRINT_ID) REFERENCES TODOUSER.SPRINT(SPRINT_ID)
);

CREATE TABLE TODOUSER.ASSIGNEDDEV(
    TODOITEM_ID NUMBER NOT NULL,
    EMPLOYEE_ID NUMBER NOT NULL,

    CONSTRAINT PK_ASSIGNEDDEV PRIMARY KEY(TODOITEM_ID, EMPLOYEE_ID),
    CONSTRAINT ASSIGNEDDEV_TODOITEM_FK FOREIGN KEY(TODOITEM_ID) 
    REFERENCES TODOUSER.TODOITEM(TODOITEM_ID) ON DELETE CASCADE,
    CONSTRAINT ASSIGNEDDEV_EMPLOYEE_FK FOREIGN KEY(EMPLOYEE_ID) 
    REFERENCES TODOUSER.EMPLOYEE(EMPLOYEE_ID) ON DELETE CASCADE
);

CREATE TABLE TODOUSER.SUBTODOITEM(
    TODOITEM_ID NUMBER NOT NULL,
    SUBTODOITEM_ID NUMBER NOT NULL,

    CONSTRAINT PK_SUBTODOITEM PRIMARY KEY(TODOITEM_ID, SUBTODOITEM_ID),
    CONSTRAINT SUBTODOITEM_TODOITEM_FK FOREIGN KEY(TODOITEM_ID) 
    REFERENCES TODOUSER.TODOITEM(TODOITEM_ID),
    CONSTRAINT SUBTODOITEM_SUBTODOITEM_FK FOREIGN KEY(SUBTODOITEM_ID) 
    REFERENCES TODOUSER.TODOITEM(TODOITEM_ID)
);

COMMIT;

-- -- SPRINT 1 DATA -- -- 

-- Insert Project
INSERT INTO TODOUSER.PROJECT (NAME) 
VALUES ('TEAM 11 Oracle Java');

-- Insert Sprint
INSERT INTO TODOUSER.SPRINT (PROJECT_ID, NAME, START_DATE, END_DATE) 
VALUES (1, 'Sprint 1 (week 1 and 2)', TO_DATE('2025-03-24', 'YYYY-MM-DD'), TO_DATE('2025-04-04', 'YYYY-MM-DD'));

-- Insert Employees
INSERT INTO TODOUSER.EMPLOYEE (NAME, MANAGER_ID, EMAIL, PASSWORD, PROJECT_ID, TELEGRAM_ID) 
VALUES ('Angel E.', NULL, 'angel@gmail.com', 'AngelPassword', 1, NULL);

INSERT INTO TODOUSER.EMPLOYEE (NAME, MANAGER_ID, EMAIL, PASSWORD, PROJECT_ID, TELEGRAM_ID) 
VALUES ('Victor J.', 1, 'victor@gmail.com', 'victorPassword', 1, NULL);

INSERT INTO TODOUSER.EMPLOYEE (NAME, MANAGER_ID, EMAIL, PASSWORD, PROJECT_ID, TELEGRAM_ID) 
VALUES ('Karen C.', 1, 'karen@gmail.com', 'karenPassword', 1, NULL);

INSERT INTO TODOUSER.EMPLOYEE (NAME, MANAGER_ID, EMAIL, PASSWORD, PROJECT_ID, TELEGRAM_ID) 
VALUES ('Carlos M.', 1, 'carlos@gmail.com', 'carlosPassword', 1, NULL);

INSERT INTO TODOUSER.EMPLOYEE (NAME, MANAGER_ID, EMAIL, PASSWORD, PROJECT_ID, TELEGRAM_ID) 
VALUES ('Milan de A.', 1, 'milan@gmail.com', 'milanPassword', 1, NULL);

INSERT INTO TODOUSER.EMPLOYEE (NAME, MANAGER_ID, EMAIL, PASSWORD, PROJECT_ID, TELEGRAM_ID) 
VALUES ('Valeria A.', 1, 'valeria@gmail.com', 'valeriaPassword', 1, NULL);

-- Insert TODOITEMS
INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Sprint 1 (Project Administration)', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-03-24 16:57:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-01 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Dear students, ir', 2);

INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Sprint 1 (Challenge) (Ken)', 'PENDING', 1, TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-04 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'For M12, this is', 1);

INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Sprint 1 (Java) (Rodrigo)', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-03 10:57:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-03-28 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-05 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Implementado k', 4);

INSERT INTO TODOUSER.TODOITEM(NAME, STATUS, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES('Sprint 1 (Requirements) (Luis)', 'PENDING', 1, TO_TIMESTAMP_TZ('2025-03-26 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-08 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Definir los sprints con base a las historias de usuario', 2);

INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Add task by developer', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-01 11:25:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-04 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Developer agrega tarea', 4);

INSERT INTO TODOUSER.TODOITEM(NAME, STATUS, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES('Assign task to sprint', 'PENDING', 1, TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-02 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Se asigna todoitem a developer', 2);

INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Reconocimiento usuario de Telegram (telefono /id) conexion con telegram', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-03 11:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Se puede conectar con telegram', 4);

INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Complete task', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-01 16:52:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-04 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Una tarea se marca como completada', 4);

INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Sprint 1 (Oracle Cloud Infrastructure) (Oswaldo)', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-03 17:15:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-04 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Avance de proyecto', 8);

-- Insert References in Assigned Developers Table
INSERT INTO ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (1, 6);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (2, 4);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (3, 5);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (4, 1);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (4, 2);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (4, 3);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (4, 5);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (4, 6);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (9, 1);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (9, 3);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (9, 4);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (9, 6);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (7, 6);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (5, 1);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (5, 4);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (6, 3);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (8, 3);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (8, 4);

-- Insert Subtask Relationships
INSERT INTO TODOUSER.SUBTODOITEM (TODOITEM_ID, SUBTODOITEM_ID) VALUES (9, 5);
INSERT INTO TODOUSER.SUBTODOITEM (TODOITEM_ID, SUBTODOITEM_ID) VALUES (9, 6);
INSERT INTO TODOUSER.SUBTODOITEM (TODOITEM_ID, SUBTODOITEM_ID) VALUES (9, 7);
INSERT INTO TODOUSER.SUBTODOITEM (TODOITEM_ID, SUBTODOITEM_ID) VALUES (9, 8);


-- -- SPRINT 2 DATA -- -- 

-- Sprint
INSERT INTO TODOUSER.SPRINT(PROJECT_ID, NAME, START_DATE, END_DATE)
VALUES(1, 'Sprint 2 (week 3 and 4)', TO_DATE('07-04-2025', 'DD-MM-YYYY'), TO_DATE('27-04-2025', 'DD-MM-YYYY'));

-- 'COMPLETED' TODOITEMS
INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Frontend manager page toggle', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-18 13:13:36 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-09 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-19 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Create a toggle to switch from completed to pending tasks', 2);
INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Frontend manager filter', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-18 16:13:36 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-09 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-19 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Create filter to see tasks by specific developer', 2);
INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Telegram KPI', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-22 18:32:59 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-13 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-19 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Add functionality of KPI visualization for the Telegram Bot', 4);
INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Prettify Frontend', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-10 18:32:59 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-04 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-12 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Modify the elements of the frontend', 4);
INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('New endpoint 1', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-12 10:38:59 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-04 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-12 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Create endpoint get pending tasks by devId and SprintId', 1);
INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('New endpoint 2', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-18 11:13:36 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-04 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-12 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Create endpoint get completed tasks by devId and SprintId', 1);

-- 'PENDING' TODOITEMS
INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('New endpoint 3', 'PENDING', 1, TO_TIMESTAMP_TZ('2025-04-04 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-15 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Create endpoint to get worked hours by devId and sprintId', 1);
INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('New endpoint 4', 'PENDING', 1, TO_TIMESTAMP_TZ('2025-04-04 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-15 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Create endpoint to get worked hours by teamId and sprintId', 1);
INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Frontend charts page 1', 'PENDING', 1, TO_TIMESTAMP_TZ('2025-04-13 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-19 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Create charts for the whole team by sprint', 4);
INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Frontend charts page 2', 'PENDING', 1, TO_TIMESTAMP_TZ('2025-04-13 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-19 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Create charts for developer by sprint', 4);
INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Frontend dev page', 'PENDING', 1, TO_TIMESTAMP_TZ('2025-04-09 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-19 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Create toggle to switch from completed to pending tasks', 2);
INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Backend/frontend integration', 'PENDING', 1, TO_TIMESTAMP_TZ('2025-04-20 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-24 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Integrate the new frontend and the changes to the backend', 4);
INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Deploy', 'PENDING', 1, TO_TIMESTAMP_TZ('2025-04-23 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-24 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Deploy the application in K8', 4);

-- AssignedDev
INSERT INTO TODOUSER.ASSIGNEDDEV(EMPLOYEE_ID, TODOITEM_ID) VALUES(2, 6);
INSERT INTO TODOUSER.ASSIGNEDDEV(EMPLOYEE_ID, TODOITEM_ID) VALUES(2, 7);
INSERT INTO TODOUSER.ASSIGNEDDEV(EMPLOYEE_ID, TODOITEM_ID) VALUES(2, 8);
INSERT INTO TODOUSER.ASSIGNEDDEV(EMPLOYEE_ID, TODOITEM_ID) VALUES(2, 9);
INSERT INTO TODOUSER.ASSIGNEDDEV(EMPLOYEE_ID, TODOITEM_ID) VALUES(3, 1);
INSERT INTO TODOUSER.ASSIGNEDDEV(EMPLOYEE_ID, TODOITEM_ID) VALUES(3, 2);
INSERT INTO TODOUSER.ASSIGNEDDEV(EMPLOYEE_ID, TODOITEM_ID) VALUES(3, 5);
INSERT INTO TODOUSER.ASSIGNEDDEV(EMPLOYEE_ID, TODOITEM_ID) VALUES(3, 12);
INSERT INTO TODOUSER.ASSIGNEDDEV(EMPLOYEE_ID, TODOITEM_ID) VALUES(4, 13);
INSERT INTO TODOUSER.ASSIGNEDDEV(EMPLOYEE_ID, TODOITEM_ID) VALUES(4, 14);
INSERT INTO TODOUSER.ASSIGNEDDEV(EMPLOYEE_ID, TODOITEM_ID) VALUES(5, 10);
INSERT INTO TODOUSER.ASSIGNEDDEV(EMPLOYEE_ID, TODOITEM_ID) VALUES(5, 11);
INSERT INTO TODOUSER.ASSIGNEDDEV(EMPLOYEE_ID, TODOITEM_ID) VALUES(6, 3);


-- -- SPRINT 3 DATA -- --
-- Sprint insertion
INSERT INTO TODOUSER.SPRINT(PROJECT_ID, NAME, START_DATE, END_DATE)
VALUES(1, 'Sprint 3 (week 5 and 6)', TO_DATE('28-04-2025', 'DD-MM-YYYY'), TO_DATE('19-05-2025', 'DD-MM-YYYY'));

-- TODOITEMS insertions
INSERT INTO TODOUSER.TODOITEM(NAME, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES ('Transform manager header into component', 1, TO_TIMESTAMP_TZ('2025-04-28 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
        TO_TIMESTAMP_TZ('2025-05-02 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Make the header of the manager visualization pages into a component', 2);

INSERT INTO TODOUSER.TODOITEM(NAME, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES ('Transform developer header into component', 1, TO_TIMESTAMP_TZ('2025-04-28 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
        TO_TIMESTAMP_TZ('2025-04-28 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Make the header of the developer visualization pages into a component', 2);

INSERT INTO TODOUSER.TODOITEM(NAME, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES ('Make carousel for selecting sprints', 1, TO_TIMESTAMP_TZ('2025-04-28 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
        TO_TIMESTAMP_TZ('2025-05-06 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Create the carousel for selecting history of sprints', 5);

INSERT INTO TODOUSER.TODOITEM(NAME, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES ('Create the button to redirect to carousel page', 1, TO_TIMESTAMP_TZ('2025-04-28 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
        TO_TIMESTAMP_TZ('2025-05-06 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Create a button in all manager pages to redirect to carousel selection page for sprint', 1);

INSERT INTO TODOUSER.TODOITEM(NAME, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES ('Make template for carousel', 1, TO_TIMESTAMP_TZ('2025-04-28 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
        TO_TIMESTAMP_TZ('2025-05-06 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Make a mock page (no backend connection) to select a different sprint', 4);

INSERT INTO TODOUSER.TODOITEM(NAME, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES ('New KPI Endpoint', 1, TO_TIMESTAMP_TZ('2025-04-28 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
        TO_TIMESTAMP_TZ('2025-05-02 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Create the endpoint of get % of overdue tasks by devId', 1);

INSERT INTO TODOUSER.TODOITEM(NAME, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES ('New KPI Endpoint', 1, TO_TIMESTAMP_TZ('2025-04-28 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
        TO_TIMESTAMP_TZ('2025-05-02 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Create the endpoint of get % of overdue tasks by devId and sprintId', 2);

INSERT INTO TODOUSER.TODOITEM(NAME, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES ('Login sprint info', 1, TO_TIMESTAMP_TZ('2025-04-28 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
        TO_TIMESTAMP_TZ('2025-05-02 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Make the telegram bot echo the info of the actual sprint when an authentication is made', 1);

INSERT INTO TODOUSER.TODOITEM(NAME, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES ('Change the endpoint of the telegram bot', 1, TO_TIMESTAMP_TZ('2025-04-28 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
        TO_TIMESTAMP_TZ('2025-05-02 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Make the telegram bot only return the tasks of the actual sprint', 1);

INSERT INTO TODOUSER.TODOITEM(NAME, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES ('Make better flow for task creation', 1, TO_TIMESTAMP_TZ('2025-04-28 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
        TO_TIMESTAMP_TZ('2025-05-02 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Make the telegram bot ask for all the needed information of a task', 2);

INSERT INTO TODOUSER.TODOITEM(NAME, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES ('Change flow of create task', 1, TO_TIMESTAMP_TZ('2025-04-28 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
        TO_TIMESTAMP_TZ('2025-05-09 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Make sure that there is the proper flow of task and subtask creation', 2);

INSERT INTO TODOUSER.TODOITEM(NAME, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES ('Connect Edit task endpoints', 1, TO_TIMESTAMP_TZ('2025-04-28 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
        TO_TIMESTAMP_TZ('2025-05-02 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Connect the endpoints of manager page to edit an existing task', 2);

INSERT INTO TODOUSER.TODOITEM(NAME, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES ('Connect carousel to backend', 1, TO_TIMESTAMP_TZ('2025-05-06 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
        TO_TIMESTAMP_TZ('2025-05-09 12:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Connect the endpoints of manager page to edit an existing task', 2);

-- Subtasks insertions
INSERT INTO TODOUSER.SUBTODOITEM(TODOITEM_ID, SUBTODOITEM_ID) VALUES (23, 24);
INSERT INTO TODOUSER.SUBTODOITEM(TODOITEM_ID, SUBTODOITEM_ID) VALUES (25, 26);
INSERT INTO TODOUSER.SUBTODOITEM(TODOITEM_ID, SUBTODOITEM_ID) VALUES (25, 27);

-- Assigning developers
-- Assign to Karen
INSERT INTO TODOUSER.ASSIGNEDDEV(TODOITEM_ID, EMPLOYEE_ID) VALUES (23, 3);
INSERT INTO TODOUSER.ASSIGNEDDEV(TODOITEM_ID, EMPLOYEE_ID) VALUES (24, 3);
INSERT INTO TODOUSER.ASSIGNEDDEV(TODOITEM_ID, EMPLOYEE_ID) VALUES (25, 3);
INSERT INTO TODOUSER.ASSIGNEDDEV(TODOITEM_ID, EMPLOYEE_ID) VALUES (26, 3);
INSERT INTO TODOUSER.ASSIGNEDDEV(TODOITEM_ID, EMPLOYEE_ID) VALUES (27, 3);

-- Assign to Victor
INSERT INTO TODOUSER.ASSIGNEDDEV(TODOITEM_ID, EMPLOYEE_ID) VALUES (28, 1);
INSERT INTO TODOUSER.ASSIGNEDDEV(TODOITEM_ID, EMPLOYEE_ID) VALUES (29, 1);

-- Assign to Valeria
INSERT INTO TODOUSER.ASSIGNEDDEV(TODOITEM_ID, EMPLOYEE_ID) VALUES (30, 6);
INSERT INTO TODOUSER.ASSIGNEDDEV(TODOITEM_ID, EMPLOYEE_ID) VALUES (31, 6);
INSERT INTO TODOUSER.ASSIGNEDDEV(TODOITEM_ID, EMPLOYEE_ID) VALUES (32, 6);

-- Assign to Carlos
INSERT INTO TODOUSER.ASSIGNEDDEV(TODOITEM_ID, EMPLOYEE_ID) VALUES (33, 4);
INSERT INTO TODOUSER.ASSIGNEDDEV(TODOITEM_ID, EMPLOYEE_ID) VALUES (34, 4);
INSERT INTO TODOUSER.ASSIGNEDDEV(TODOITEM_ID, EMPLOYEE_ID) VALUES (35, 4);
