-- Insert Project
INSERT INTO TODOUSER.PROJECT (NAME) 
VALUES ('TEAM 11 Oracle Java');

-- Insert Sprint
INSERT INTO TODOUSER.SPRINT (PROJECT_ID, NAME, START_DATE, END_DATE) 
VALUES (1, 'Sprint 1 (week 1 and 2)', TO_DATE('2025-03-24', 'YYYY-MM-DD'), TO_DATE('2025-04-04', 'YYYY-MM-DD'));

-- Insert Employees
INSERT INTO TODOUSER.EMPLOYEE (NAME, MANAGER_ID, EMAIL, PASSWORD, PROJECT_ID, TELEGRAM_ID) 
VALUES ('Angel E.', NULL, 'angel@gmail.com', 'AngelPassword', 1, NULL);

INSERT INTO TODOUSER.EMPLOYEE (NAME, MANAGER_ID, EMAIL, PASSWORD, PROJECT_ID, TELEGRAM_ID) 
VALUES ('Victor J.', 1, 'victor@gmail.com', 'victorPassword', 1, NULL);

INSERT INTO TODOUSER.EMPLOYEE (NAME, MANAGER_ID, EMAIL, PASSWORD, PROJECT_ID, TELEGRAM_ID) 
VALUES ('Karen C.', 1, 'karen@gmail.com', 'karenPassword', 1, NULL);

INSERT INTO TODOUSER.EMPLOYEE (NAME, MANAGER_ID, EMAIL, PASSWORD, PROJECT_ID, TELEGRAM_ID) 
VALUES ('Carlos M.', 1, 'carlos@gmail.com', 'carlosPassword', 1, NULL);

INSERT INTO TODOUSER.EMPLOYEE (NAME, MANAGER_ID, EMAIL, PASSWORD, PROJECT_ID, TELEGRAM_ID) 
VALUES ('Milan de A.', 1, 'milan@gmail.com', 'milanPassword', 1, NULL);

INSERT INTO TODOUSER.EMPLOYEE (NAME, MANAGER_ID, EMAIL, PASSWORD, PROJECT_ID, TELEGRAM_ID) 
VALUES ('Valeria A.', 1, 'valeria@gmail.com', 'valeriaPassword', 1, NULL);

-- Insert TODOITEMS
INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Sprint 1 (Project Administration)', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-03-24 16:57:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-01 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Dear students, ir', 2);

INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Sprint 1 (Challenge) (Ken)', 'PENDING', 1, TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-04 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'For M12, this is', 1);

INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Sprint 1 (Java) (Rodrigo)', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-03 10:57:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-03-28 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-05 00:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Implementado k', 4);

INSERT INTO TODOUSER.TODOITEM(NAME, STATUS, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES('Sprint 1 (Requirements) (Luis)', 'PENDING', 1, TO_TIMESTAMP_TZ('2025-03-26 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-08 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Definir los sprints con base a las historias de usuario', 2);

INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Add task by developer', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-01 11:25:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-04 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Developer agrega tarea', 4);

INSERT INTO TODOUSER.TODOITEM(NAME, STATUS, MANAGER_ID, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS)
VALUES('Assign task to sprint', 'PENDING', 1, TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-02 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Se asigna todoitem a developer', 2);

INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Reconocimiento usuario de Telegram (telefono /id) conexion con telegram', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-03 11:00:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Se puede conectar con telegram', 4);

INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Complete task', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-01 16:52:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-04 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Una tarea se marca como completada', 4);

INSERT INTO TODOUSER.TODOITEM (NAME, STATUS, MANAGER_ID, COMPLETION_TS, START_DATE, DEADLINE, SPRINT_ID, DESCRIPTION, EST_HOURS) 
VALUES ('Sprint 1 (Oracle Cloud Infrastructure) (Oswaldo)', 'COMPLETED', 1, TO_TIMESTAMP_TZ('2025-04-03 17:15:00 -06:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-03-24 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), TO_TIMESTAMP_TZ('2025-04-04 00:00:00 -06:00' , 'YYYY-MM-DD HH24:MI:SS TZH:TZM'), 1, 'Avance de proyecto', 8);

-- Insert References in Assigned Developers Table
INSERT INTO ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (1, 6);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (2, 4);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (3, 5);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (4, 1);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (4, 2);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (4, 3);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (4, 5);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (4, 6);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (9, 1);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (9, 3);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (9, 4);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (9, 6);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (7, 6);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (5, 1);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (5, 4);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (6, 3);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (8, 3);
INSERT INTO TODOUSER.ASSIGNEDDEV (TODOITEM_ID, EMPLOYEE_ID) VALUES (8, 4);

-- Insert Subtask Relationships
INSERT INTO TODOUSER.SUBTODOITEM (TODOITEM_ID, SUBTODOITEM_ID) VALUES (9, 5);
INSERT INTO TODOUSER.SUBTODOITEM (TODOITEM_ID, SUBTODOITEM_ID) VALUES (9, 6);
INSERT INTO TODOUSER.SUBTODOITEM (TODOITEM_ID, SUBTODOITEM_ID) VALUES (9, 7);
INSERT INTO TODOUSER.SUBTODOITEM (TODOITEM_ID, SUBTODOITEM_ID) VALUES (9, 8);
